# Generated by Django 5.2.3 on 2025-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_key',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
